akiogitgit/share-pos

src/components/postForm.tsx, src/hooks/useLogin.ts, src/pages/create.tsx, src/pages/index.tsx, src/pages/login.tsx, src/types/post.ts, src/types/response.ts
- 投稿ページの作成 pages/ create
- 投稿formのコンポーネント作成 components/ postForm
1.  /loginでログインする(ログインしないと401)
2. /create で投稿情報を入力 (inputにrequireついてるから、エラーにならない)
3. 投稿が成功すると、useRouterで index に遷移する
=> 記事の投稿機能の作成

next.config.js, src/components/PostItem.tsx, src/components/postForm.tsx, src/pages/create.tsx, src/pages/index.tsx, src/types/post.ts, src/utils/api.ts, src/utils/toCamelCaseObj.ts
=> 各Postのurl のサムネイル画像を表示

src/components/post/PostStars.tsx, src/pages/index.tsx
=> PostStarsのベース作成

src/pages/index.tsx
=> indexのpostをgridで表示

src/components/auth/LoginForm.tsx, src/components/auth/SignUpForm.tsx, src/components/bookmark/BookmarkFolderList.tsx, src/components/layout/Footer.tsx, src/components/layout/Header.tsx, src/components/post/Item/FolderList.tsx, src/components/post/Item/PostItem.tsx, src/components/post/Item/PostMenuButton.tsx, src/components/post/PostForm.tsx, src/pages/myPage.tsx
アイコンを読み込むとき、`as` で○○Iconという名前で使用する。
=> アイコンを使うとき、○○Icon にする

src/components/post/Item/PostItem.tsx, src/pages/bookmark.tsx, src/pages/index.tsx, src/pages/myPage.tsx
#53 
mapで配列を回すとき、keyにindexを渡していたのを、別の値に置き換える
=> fix: keyにindexを渡さない

src/pages/index.tsx, src/stores/useCookies.ts, src/utils/api.ts, src/utils/encryptedCookie.ts
フロントが自分でCookieにtokenを入れた時、Railsが取得できるかをスマホで試すためのテスト
=> フロントがtokenをCookieに入れる

package.json, src/components/bookmark/BookmarkFolderList.tsx, src/components/bookmark/FolderEditModal.tsx, src/components/layout/Footer.tsx, src/components/layout/Header.tsx, src/components/post/Item/FolderList.tsx, src/components/post/Item/PostItem.tsx, src/hooks/useBookmark.ts, src/hooks/useFolder.ts, src/pages/bookmark.tsx, src/types/bookmark.ts, src/types/post.ts, yarn.lock
- #51 
- Headless UI の導入
- ブックマークページの、フォルダ名更新・フォルダ削除の動作をモーダルで実装
- bookmark.tsx で定義していたselectedFolderIndexを、再度selectedFolderId に修正
- bookmark.tsxのselectedIdを、BookmarkFolderListに渡して使用し、FolderEditModalにも渡して使用する。
- ↓　bookmark.tsx
- ↓　BookmarkFolderList
- FolderEditModal
1. フォルダを1度押すと、選択されてフォルダ内の記事を表示
2. 2連続でフォルダを押すと、モーダルが開く
3. 更新を押すとフォルダ名が更新される
1. モーダルが出た状態で、赤い✕ボタンを押す
2. 削除の確認メッセージが出る。
3. 削除を押すとフォルダが削除される
- 1度タップするとフォルダを選択して、その中の記事を表示する。
- 2度目のタップで、編集モーダルを表示
- フォルダ名を変えて、更新を押すと更新される
- フォルダを削除する時は、赤い✕ボタンを押す。
- 確認メッセージを表示、削除を押すとフォルダを削除する
=> フォルダ編集・削除モーダルの作成

src/components/bookmark/CreateFolderField.tsx, src/components/bookmark/FolderEditModal.tsx, src/components/layout/Layout.tsx, src/components/shares/Modal.tsx, src/pages/bookmark.tsx, src/pages/users/[id].tsx
自作アニメーションを削除、、
Modalコンポーネント作成
新規フォルダ作成画面を、モーダルで表示
=> 新規フォルダ作成をモーダルに変更

src/components/bookmark/CreateFolderButton.tsx, src/components/post/Item/FolderList.tsx, src/components/shares/Modal.tsx, src/pages/bookmark.tsx
- PostItemの`ブックマークに追加`に`新規フォルダ作成`のボタンを追加
- Modalコンポーネントを修正
- CreateFolderButtonのclassを呼び出す側で変える
before
after
=> PostItemのブックマークに、新規フォルダ作成ボタンを追加

src/pages/index.tsx, src/utils/api.ts
=> feat: flyにデプロイしたapiと接続

package.json, src/components/bookmark/CreateFolderButton.tsx, src/components/shares/button/JumpToCreatePostButton.tsx, yarn.lock
=> feat: 下スクロールで、右下の投稿ボタンをアニメーション

src/components/shares/button/JumpToCreatePostButton.tsx
=> fix: 横幅を足す

src/components/shares/button/JumpToCreatePostButton.tsx
=> feat: 画面上らへんだと表示する

next.config.js, src/components/layout/header/DropDownMenu.tsx, src/components/post/Item/PostItem.tsx, src/components/shares/Avatar.tsx, src/components/shares/button/Button.tsx, src/pages/users/[id].tsx, src/pages/users/index.tsx
- #68
- Gravatarにuser.idを渡して、ユーザーアイコンを生成
- ヘッダー、PostItem、マイページにアイコンを追加
- Avatarコンポーネント作成
- Buttonコンポーネントに、variant="default"を追加
- ヘッダー、PostItem
ログイン前
ログイン後
- マイページ
自分の時
他の人の時
=> ユーザーアイコンを作成

src/components/post/Item/PostItem.tsx
- #77 
PostItemに影を追加
before
after
=> feat: PostItemに影を追加

src/components/layout/Footer.tsx, src/components/layout/header/Header.tsx, src/components/shares/button/index.ts
- スマホの時だけ、ヘッダーにスクロールアニメーションを追加
=> feat: スマホの時、ヘッダーにスクロールアニメーション追加

src/components/bookmark/BookmarkFolderEditModal.tsx, src/components/bookmark/BookmarkFolderList.tsx, src/components/post/PostComment.tsx, src/components/post/PostItem.tsx, src/components/post/PostMenuButton.tsx, src/components/shares/AvatarDropDownMenu.tsx, src/components/shares/CreateFolderButton.tsx, src/components/user/UserCard.tsx, src/components/user/UserProfile.tsx, src/hooks/useBoolean.ts, src/pages/bookmark.tsx, src/pages/test.tsx
- #154
- boolean用のカスタムフック作成
- 既存のuseStateでboolean型を使ってるものを、useBooleanで置き換える
返り値
```typescript
{
v: boolean,
setTrue: () => setBoolean(true),
setFalse: () => setBoolean(false),
toggle: () => setBoolean(v => !v),
}
```
=> feat: useBoolean作成

src/components/post/PostForm.tsx
- ミスで、PostFormのcommentを、min: 100にしていたので修正
=> fix: PostFormのバリデーション修正

src/components/auth/LoginForm.tsx, src/components/auth/SignUpForm.tsx, src/components/bookmark/BookmarkFolderEditModal.tsx, src/components/bookmark/BookmarkFolderList.tsx, src/components/layout/Footer.tsx, src/components/layout/Header.tsx, src/components/post/PostFolderList.tsx, src/components/post/PostForm.tsx, src/components/post/PostLinkCard.tsx, src/components/post/PostMenuButton.tsx, src/components/shares/AvatarDropDownMenu.tsx, src/components/shares/CreateFolderButton.tsx, src/components/shares/JumpToCreatePostButton.tsx, src/components/shares/base/Alert.tsx, src/components/shares/base/DropDownMenu.tsx, src/components/shares/base/Loader.tsx, src/components/user/UserCard.tsx, src/components/user/UserProfile.tsx, src/pages/index.tsx, src/pages/login.tsx, src/pages/signup.tsx, src/pages/test.tsx, src/pages/users/[id].tsx
- #176 
WAI-ARIAの role, aria-*, tabindexを使い、目をつぶっても操作できるようにする。
- aria-labelでフォーカスした時に要素の説明する
- フォーム
- aria-required　入力の必須
- role="alert"　エラーメッセージを読み上げる
- トグルメニュー
- aria-pressed
- タブ
- role="tablist" role="tab"
- モーダル
- フォームと同じ
- フッターメニュー
- role="menu" role="menuitem"
- aria-current
- ヘッダー
- ヘッダーのSharePos
- aria-label　シェアポス、読んで良かった記事をシェアするサービス
- ヘッダーアイコンメニュー
- aria-label, aria-pressed　メニューを開くボタン。開かれていません
- ヘッダー検索ボタン
- まだ機能はないけど、role="search" tabIndex=0
- シェアするにaria-label
- PostItemの・・・(PostMenuButton)
- aria-label, aria-pressed
- PostMenuを<ul>にする
- LinkForm
- aria-labelを修正
- フォーム
- aria-requiredで必須を伝える
- バリデーションエラーが出ている時、aria-invalid="true"で正しくないことを伝える
- バリデーションエラー、サーバーエラーメッセージにrole="alert"を付けて、自動で読み上げる
- login.tsx, sigin.tsx
- ログインはこちらの、こちらにaria-label
- Loaderコンポーネント
- …
=> スクリーンリーダーを正しく設定する

.husky/commit-msg, .husky/pre-commit, .husky/pre-push, .lintstagedrc.json, changelog.config.js, commitlint.config.js, package.json, pnpm-lock.yaml
以下を導入
- husky
- lintstaged
- commitlint
- git-cz
=> コミット・プッシュのリンター追加

.github/auto_assign.yml
=> feat: 自動アサイン、レビュワー設定を追加

.github/auto_assign.yml
=> fix: PRアサインを自分になるように修正
